import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'id' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  id: {
    // Navbar
    'nav.about': 'Tentang',
    'nav.modules': 'Modul',
    'nav.impact': 'Dampak',
    'nav.products': 'Produk',
    'nav.products.generator': 'AI Product Generator',
    'nav.products.marketplace': 'Rural Marketplace',
    'nav.myProfile': 'My Profile',
    
    // Hero Section
    'hero.title': 'Transformasi Potensi Desa',
    'hero.title2': 'Menjadi Pertumbuhan Ekonomi Cerdas',
    'hero.subtitle': 'Platform AI milik komunitas untuk menemukan, mengembangkan, dan mendistribusikan nilai dari sumber daya lokal',
    'hero.join': 'Daftar Mitra Desa',
    'hero.learnMore': 'Pelajari Lebih Lanjut',
    'hero.watchDemo': 'Tonton Demo',
    
    // Landing Page Sections
    'landing.modules.title': 'Modul Platform RIN',
    'landing.modules.subtitle': 'Ekosistem lengkap untuk transformasi ekonomi desa',
    'landing.impact.title': 'Dampak Nyata',
    'landing.impact.subtitle': 'Hasil yang terukur untuk komunitas',
    'landing.products.title': 'Produk & Layanan',
    'landing.products.subtitle': 'Solusi lengkap untuk desa',
    
    // About Section
    'about.title': 'Apa itu RIN?',
    'about.description': 'Platform ekonomi pedesaan bertenaga AI yang dimiliki oleh komunitas untuk memberdayakan desa dalam menemukan, mengembangkan, dan mendistribusikan nilai dari sumber daya lokal.',
    'about.data.title': 'Data-Driven',
    'about.data.desc': 'Digitalisasi aset ekonomi desa menjadi data yang dapat ditindaklanjuti',
    'about.ai.title': 'AI-Powered',
    'about.ai.desc': 'Analisis cerdas untuk pengambilan keputusan strategis',
    'about.market.title': 'Market Access',
    'about.market.desc': 'Koneksi langsung ke pasar dengan harga transparan',
    
    // Modules Section
    'modules.title': 'Modul Platform',
    'modules.description': 'Ekosistem lengkap untuk transformasi ekonomi desa',
    'modules.data.title': 'Community Data Engine',
    'modules.data.desc': 'Digitalisasi aset ekonomi desa, komoditas, dan kapabilitas menjadi data yang dapat ditindaklanjuti',
    'modules.translator.title': 'AI Economic Translator',
    'modules.translator.desc': 'Transformasi data desa mentah menjadi insight pasar, strategi harga, dan proyeksi permintaan',
    'modules.generator.title': 'AI Product Generator',
    'modules.generator.desc': 'Ideasi produk berbasis AI dari komoditas lokal dengan analisis margin dan skor kelayakan',
    'modules.marketplace.title': 'Rural Market Link',
    'modules.marketplace.desc': 'Marketplace langsung menghubungkan desa dengan pembeli menggunakan harga transparan dan smart contracts',
    'modules.impact.title': 'Impact Dashboard',
    'modules.impact.desc': 'Pelacakan metrik dampak sosial dan ekonomi real-time untuk stakeholder',
    
    // Impact Section
    'impact.title': 'Dampak Nyata',
    'impact.description': 'Hasil yang terukur untuk komunitas',
    'impact.villages': 'Desa Bermitra',
    'impact.products': 'Produk Dihasilkan',
    'impact.transactions': 'Total Transaksi',
    'impact.growth': 'Revenue Growth',
    
    // Showcase Section
    'showcase.title': 'Coba AI Product Generator',
    'showcase.description': 'Lihat bagaimana AI kami menghasilkan rekomendasi produk dari komoditas lokal',
    'showcase.try': 'Coba sekarang',
    'showcase.from': 'dari',
    'showcase.margin': 'Margin',
    'showcase.target': 'Target Pasar',
    
    // Generator Commodities
    'generator.corn': 'Jagung',
    'generator.seaweed': 'Rumput Laut',
    'generator.moringa': 'Kelor',
    
    // Marketplace Section
    'marketplace.description': 'Pasar digital untuk produk desa berkualitas',
    'marketplace.browse': 'Jelajahi Produk',
    'marketplace.capacity': 'Kapasitas',
    
    // Footer
    'footer.description': 'Platform AI milik komunitas yang memberdayakan desa untuk menemukan, mengembangkan, dan mendistribusikan nilai dari sumber daya lokal.',
    'footer.rights': 'Hak Cipta Dilindungi. Powered by Timur Network Foundation.',
    
    // Community Data Engine
    'dataEngine.title': 'Community Data Engine',
    'dataEngine.subtitle': 'Masukkan aset ekonomi dan kapasitas produksi desa Anda',
    'dataEngine.step1': 'Data Desa',
    'dataEngine.step2': 'Data PIC',
    'dataEngine.step3': 'Data Lokasi',
    'dataEngine.step4': 'Data Produksi',
    'dataEngine.step5': 'Aset Komunitas',
    'dataEngine.step6': 'Tinjau',
    
    // Step 1: Village Data
    'step1.title': 'Data Desa',
    'step1.villageName': 'Nama Desa',
    'step1.villageName.placeholder': 'Masukkan nama desa',
    'step1.villageType': 'Jenis Desa',
    'step1.villageType.placeholder': 'Pilih jenis desa',
    'step1.villageType.agricultural': 'Pertanian',
    'step1.villageType.coastal': 'Pesisir',
    'step1.villageType.mountain': 'Pegunungan',
    'step1.population': 'Jumlah Penduduk',
    'step1.population.placeholder': 'Masukkan jumlah penduduk',
    
    // Step 2: PIC Data
    'step2.title': 'Data Penanggung Jawab',
    'step2.picName': 'Nama Penanggung Jawab',
    'step2.picName.placeholder': 'Masukkan nama PIC',
    'step2.picRole': 'Jabatan',
    'step2.picRole.placeholder': 'Masukkan jabatan',
    'step2.picPhone': 'Nomor Telepon',
    'step2.picPhone.placeholder': 'Masukkan nomor telepon',
    'step2.picEmail': 'Email',
    'step2.picEmail.placeholder': 'Masukkan email',
    'step2.fullName': 'Nama Lengkap',
    'step2.fullName.placeholder': 'Masukkan nama lengkap',
    'step2.whatsapp': 'WhatsApp',
    'step2.whatsapp.placeholder': 'Nomor WhatsApp',
    'step2.instagram': 'Instagram',
    'step2.instagram.placeholder': 'Username Instagram',
    'step2.tiktok': 'TikTok',
    'step2.tiktok.placeholder': 'Username TikTok',
    'step2.website': 'Website',
    'step2.website.placeholder': 'URL Website',
    
    // Step 3: Location Data
    'step3.title': 'Data Lokasi',
    'step3.province': 'Provinsi',
    'step3.province.placeholder': 'Pilih provinsi',
    'step3.district': 'Kabupaten',
    'step3.district.placeholder': 'Masukkan kabupaten',
    'step3.subdistrict': 'Kecamatan',
    'step3.subdistrict.placeholder': 'Masukkan kecamatan',
    'step3.address': 'Alamat Lengkap',
    'step3.address.placeholder': 'Masukkan alamat lengkap',
    'step3.coordinates': 'Koordinat GPS',
    'step3.coordinates.placeholder': 'Contoh: -6.200000, 106.816666',
    'step3.rt': 'RT',
    'step3.rt.placeholder': 'Nomor RT',
    'step3.rw': 'RW',
    'step3.rw.placeholder': 'Nomor RW',
    'step3.kelurahan': 'Kelurahan',
    'step3.kelurahan.placeholder': 'Nama Kelurahan',
    'step3.kecamatan': 'Kecamatan',
    'step3.kecamatan.placeholder': 'Nama Kecamatan',
    'step3.city': 'Kota',
    'step3.city.placeholder': 'Nama Kota',
    'step3.postalCode': 'Kode Pos',
    'step3.postalCode.placeholder': 'Kode Pos',
    'step3.pinLocation': 'Pin Lokasi',
    'step3.pinLocation.placeholder': 'Link Google Maps',
    
    // Step 4: Production Data
    'step4.title': 'Data Produksi',
    'step4.description': 'Pilih komoditas yang diproduksi di desa Anda',
    'step4.selectCommodity': 'Pilih Komoditas',
    'step4.commodityType': 'Jenis Komoditas',
    'step4.addCustomCommodity': 'Tambah Komoditas Lainnya',
    'step4.addCustomCommodity.placeholder': 'Masukkan nama komoditas',
    'step4.monthlyVolume': 'Volume Produksi Bulanan',
    'step4.monthlyVolume.placeholder': 'Masukkan volume (ton)',
    'step4.qualityLevel': 'Tingkat Kualitas',
    'step4.qualityLevel.placeholder': 'Pilih kualitas',
    'step4.harvestSeason': 'Musim Panen',
    'step4.harvestSeason.placeholder': 'Masukkan musim panen',
    'button.add': 'Tambah',
    
    // Step 5: Community Assets
    'step5.title': 'Aset Komunitas',
    'step5.workforce': 'Tenaga Kerja',
    'step5.workforce.placeholder': 'Jumlah tenaga kerja tersedia',
    'step5.equipment': 'Peralatan',
    'step5.equipment.placeholder': 'Deskripsi peralatan yang dimiliki',
    'step5.infrastructure': 'Infrastruktur',
    'step5.infrastructure.placeholder': 'Deskripsi infrastruktur pendukung',
    'step5.skills': 'Keterampilan Komunitas',
    'step5.addCustomSkill': 'Tambah Keterampilan Lainnya',
    'step5.addCustomSkill.placeholder': 'Masukkan keterampilan',
    'step5.addCustomEquipment': 'Tambah Peralatan Lainnya',
    'step5.addCustomEquipment.placeholder': 'Masukkan nama peralatan',
    'step5.logistics': 'Logistik',
    'step5.addCustomLogistics': 'Tambah Logistik Lainnya',
    'step5.addCustomLogistics.placeholder': 'Masukkan jenis logistik',
    
    // Step 6: Review
    'step6.title': 'Tinjau Data',
    'step6.description': 'Periksa kembali data yang telah Anda masukkan',
    'step6.submit': 'Kirim Data',
    'step6.villageInfo': 'Informasi Desa',
    'step6.picInfo': 'Informasi Penanggung Jawab',
    'step6.locationInfo': 'Informasi Lokasi',
    'step6.productionInfo': 'Informasi Produksi',
    'step6.assetsInfo': 'Informasi Aset',
    'step6.edit': 'Edit',
    
    'dataEngine.villageName': 'Nama Desa',
    'dataEngine.province': 'Provinsi',
    'dataEngine.district': 'Kabupaten',
    'dataEngine.subdistrict': 'Kecamatan',
    'dataEngine.picName': 'Nama PIC',
    'dataEngine.picRole': 'Jabatan PIC',
    'dataEngine.picPhone': 'No. Telepon PIC',
    'dataEngine.picEmail': 'Email PIC',
    'dataEngine.address': 'Alamat Lengkap',
    'dataEngine.coordinates': 'Koordinat',
    'dataEngine.selectCommodities': 'Pilih Komoditas',
    'dataEngine.production': 'Produksi',
    'dataEngine.capacity': 'Kapasitas',
    'dataEngine.quality': 'Kualitas',
    'dataEngine.workforce': 'Tenaga Kerja',
    'dataEngine.equipment': 'Peralatan',
    'dataEngine.infrastructure': 'Infrastruktur',
    'dataEngine.review': 'Tinjau Data',
    'dataEngine.success': 'Data berhasil disimpan!',
    'dataEngine.error': 'Gagal menyimpan data',
    
    // AI Product Generator
    'generator.title': 'AI Product Generator',
    'generator.subtitle': 'Rekomendasi produk turunan dari komoditas Anda',
    'generator.selectCommodity': 'Pilih Komoditas',
    'generator.select': 'Pilih Komoditas Utama',
    'generator.generate': 'Generate Rekomendasi',
    'generator.generating': 'Generating...',
    'generator.results': 'Hasil Rekomendasi',
    'generator.productName': 'Nama Produk',
    'generator.description': 'Deskripsi',
    'generator.marketPotential': 'Potensi Pasar',
    'generator.investmentNeeded': 'Investasi Dibutuhkan',
    'generator.roi': 'ROI Estimasi',
    'generator.addToMarket': 'Tambah ke Marketplace',
    'generator.complete': 'Rekomendasi Siap',
    'generator.completeDesc': '{count} produk turunan dari {commodity} telah dihasilkan. Pilih yang paling sesuai dengan kapasitas dan target pasar Anda.',
    'generator.options': 'Opsi Produk',
    'generator.margin': 'Margin',
    'generator.cost': 'Biaya Produksi',
    'generator.price': 'Harga Jual',
    'generator.breakeven': 'Break Even',
    'generator.complexity': 'Kompleksitas',
    'generator.risk': 'Risiko',
    'generator.viewFull': 'Lihat Detail Lengkap',
    'generator.hideDetails': 'Sembunyikan Detail',
    'generator.reasoning': 'Analisis AI',
    'generator.equipment': 'Peralatan Dibutuhkan',
    'generator.shopEquipment': 'Belanja Peralatan',
    'generator.packaging': 'Kemasan',
    'generator.shopPackaging': 'Belanja Kemasan',
    'generator.cocoa': 'Kakao',
    'generator.coffee': 'Kopi',
    'generator.cassava': 'Singkong',
    'generator.others': 'Lainnya',
    'generator.othersPlaceholder': 'Masukkan komoditas lain (pisah dengan koma)',
    'generator.enterCommodity': 'Masukkan komoditas lain (pisah dengan koma)',
    'generator.analyzing': 'Menganalisis Komoditas',
    'generator.available': 'Kapasitas Tersedia',
    'generator.readyTitle': 'Siap Menghasilkan Rekomendasi Produk?',
    'generator.readyDesc': 'Pilih komoditas di atas dan klik tombol Generate untuk mendapatkan rekomendasi produk turunan yang disesuaikan dengan kapasitas dan peluang pasar Anda.',
    'generator.lowRisk': 'Rendah',
    'generator.mediumRisk': 'Sedang',
    'generator.highRisk': 'Tinggi',
    'generator.lowComplexity': 'Rendah',
    'generator.mediumComplexity': 'Sedang',
    'generator.highComplexity': 'Tinggi',
    
    // Buttons
    'button.next': 'Lanjut',
    'button.prev': 'Kembali',
    'button.submit': 'Kirim',
    'button.save': 'Simpan',
    'button.cancel': 'Batal',
    'button.close': 'Tutup',
    'button.edit': 'Edit',
    'button.delete': 'Hapus',
    'button.confirm': 'Konfirmasi',
    'button.back': 'Kembali',
    'button.continue': 'Lanjutkan',
    'button.finish': 'Selesai',
    
    // Dashboard
    'dashboard.title': 'Dashboard Desa',
    'dashboard.welcome': 'Selamat Datang',
    'dashboard.overview': 'Ringkasan',
    'dashboard.totalRevenue': 'Total Pendapatan',
    'dashboard.activePartners': 'Mitra Desa Aktif',
    'dashboard.totalProducts': 'Total Produk',
    'dashboard.commodities': 'Komoditas',
    'dashboard.recentActivity': 'Aktivitas Terbaru',
    'dashboard.statistics': 'Statistik',
    'dashboard.back': 'Kembali ke Dashboard',
    
    // AI Economic Translator
    'aet.title': 'AI Economic Translator',
    'aet.subtitle': 'Penerjemah Data Ekonomi Desa',
    'aet.priceTrend': 'Analisis Tren Harga',
    'aet.volumeAnalysis': 'Analisis Volume',
    'aet.filter.period': 'Filter Periode',
    'aet.filter.commodity': 'Filter Komoditas',
    'aet.filter.daily': 'Harian',
    'aet.filter.weekly': 'Mingguan',
    'aet.filter.monthly': 'Bulanan',
    'aet.filter.q1': 'Q1',
    'aet.filter.q2': 'Q2',
    'aet.filter.q3': 'Q3',
    'aet.filter.q4': 'Q4',
    'aet.applyFilter': 'Terapkan Filter',
    'aet.clearFilter': 'Hapus Filter',
    
    // Marketplace
    'marketplace.title': 'Rural Marketplace',
    'marketplace.subtitle': 'Pasar Digital Desa',
    'marketplace.search': 'Cari produk...',
    'marketplace.filter': 'Filter',
    'marketplace.sort': 'Urutkan',
    'marketplace.addToCart': 'Tambah ke Keranjang',
    'marketplace.viewDetails': 'Lihat Detail',
    'marketplace.price': 'Harga',
    'marketplace.stock': 'Stok',
    'marketplace.seller': 'Penjual',
    'marketplace.category': 'Kategori',
    
    // My Profile
    'profile.title': 'Profil Saya',
    'profile.activePartner': 'Mitra Desa Aktif',
    'profile.exportReport': 'Export Laporan',
    'profile.totalCommodities': 'Total Komoditas',
    'profile.monthlyProduction': 'Produksi Bulanan',
    'profile.activeProducts': 'Produk Aktif',
    'profile.currentStock': 'Stok Saat Ini',
    'profile.totalRevenue': 'Total Pendapatan',
    'profile.commodityDetails': 'Detail Komoditas',
    'profile.updateStock': 'Update Stok',
    'profile.capacity': 'Kapasitas',
    'profile.derivedProducts': 'Produk Turunan',
    'profile.monthlySales': 'Penjualan Bulan Ini',
    'profile.lastUpdate': 'Update Terakhir',
    'profile.addProduct': 'Tambah Produk',
    'profile.addSales': 'Tambah Penjualan',
    'profile.myProducts': 'Produk Saya',
    'profile.commodity': 'Komoditas',
    'profile.sellingPrice': 'Harga Jual',
    'profile.stock': 'Stok',
    'profile.sales': 'Penjualan',
    'profile.revenue': 'Revenue',
    'profile.ton': 'Ton',
    'profile.kg': 'kg',
    'profile.myProductsMarketplace': 'Produk Saya di Marketplace',
    'profile.price': 'Harga',
    'profile.sold': 'Terjual',
    'profile.viewAll': 'Lihat Semua Produk',
    'profile.aiProductGenerator': 'AI Product Generator',
    'profile.aiProductGeneratorDesc': 'Generate produk baru dari komoditas Anda',
    'profile.aiEconomicInsights': 'AI Economic Insights',
    'profile.aiEconomicInsightsDesc': 'Analisis mendalam performa bisnis Anda',
    'profile.inputSales': 'Input Penjualan',
    'profile.inputSalesDesc': 'Catat penjualan harian/mingguan/bulanan',
    'profile.manageMarketplace': 'Kelola Marketplace',
    'profile.manageMarketplaceDesc': 'Atur produk dan harga di marketplace',
    'profile.updateStockTitle': 'Update Stok Komoditas',
    'profile.updateStockDesc': 'Tambah produksi baru atau kurangi stok secara manual',
    'profile.selectCommodity': 'Pilih Komoditas',
    'profile.selectCommodityPlaceholder': '-- Pilih Komoditas --',
    'profile.updateType': 'Tipe Update',
    'profile.addProduction': 'Tambah Produksi',
    'profile.manualReduction': 'Pengurangan Manual',
    'profile.amount': 'Jumlah',
    'profile.amountPlaceholder': 'Masukkan jumlah',
    'profile.date': 'Tanggal',
    'profile.notes': 'Catatan (Opsional)',
    'profile.notesPlaceholder': 'Tambahkan catatan...',
    'profile.cancel': 'Batal',
    'profile.saveUpdate': 'Simpan Update Stok',
    'profile.saveUpdateStock': 'Simpan Update Stok',
    'profile.enterAmount': 'Masukkan jumlah',
    'profile.notesOptional': 'Catatan (Opsional)',
    'profile.addNotes': 'Tambahkan catatan...',
    'profile.selectCommodityError': 'Pilih komoditas dan masukkan jumlah',
    'profile.amountError': 'Jumlah harus lebih dari 0',
    'profile.addStockSuccess': 'Berhasil menambah {amount} ton {commodity}',
    'profile.reduceStockSuccess': 'Berhasil mengurangi {amount} ton {commodity}',
    'profile.addProductNew': 'Tambah Produk Baru',
    'profile.addProductDesc': 'Tambahkan produk baru ke marketplace Anda',
    'profile.productName': 'Nama Produk',
    'profile.productNamePlaceholder': 'Contoh: Premium Organic Corn Flour',
    'profile.category': 'Kategori',
    'profile.commodityCategory': 'Komoditas',
    'profile.processedProducts': 'Produk Olahan',
    'profile.equipment': 'Equipment',
    'profile.baseCommodity': 'Komoditas Dasar',
    'profile.baseCommodityPlaceholder': '-- Pilih Komoditas --',
    'profile.initialStock': 'Stok Awal',
    'profile.sellingPricePerKg': 'Harga Jual per Kg',
    'profile.costPricePerKg': 'Harga Modal per Kg',
    'profile.minOrder': 'Minimum Order (kg)',
    'profile.productDescription': 'Deskripsi Produk',
    'profile.productDescPlaceholder': 'Jelaskan kualitas, proses pembuatan, keunggulan produk...',
    
    // Export Report PDF
    'report.cover.title': 'LAPORAN MITRA DESA',
    'report.cover.subtitle': 'Rural Intelligence Network',
    'report.cover.partnerName': 'Nama Mitra',
    'report.cover.location': 'Lokasi',
    'report.cover.reportPeriod': 'Periode Laporan',
    'report.cover.generatedDate': 'Tanggal Generate',
    'report.cover.tagline1': 'Data bukan sekadar angka.',
    'report.cover.tagline2': 'Ini adalah fondasi pertumbuhan ekonomi desa yang berkelanjutan.',
    'report.cover.poweredBy': 'Powered by Timur Network Foundation',
    
    // Page 2: Commodity Profile
    'report.commodity.title': 'PROFIL KOMODITAS',
    'report.commodity.name': 'Komoditas',
    'report.commodity.currentStock': 'Stok Saat Ini',
    'report.commodity.capacity': 'Kapasitas',
    'report.commodity.production': 'Produksi/Bulan',
    'report.commodity.lastUpdate': 'Update Terakhir',
    'report.commodity.totalStock': 'Total Stok Keseluruhan',
    'report.commodity.utilization': 'Tingkat Utilisasi',
    'report.commodity.ton': 'ton',
    
    // Page 3: Sales Data
    'report.sales.title': 'DATA PENJUALAN',
    'report.sales.totalVolume': 'Total Volume Terjual',
    'report.sales.totalTransactions': 'Total Transaksi',
    'report.sales.totalRevenue': 'Total Revenue',
    'report.sales.topByVolume': 'Produk Terlaris (Volume)',
    'report.sales.topByRevenue': 'Produk Revenue Tertinggi',
    'report.sales.product': 'Produk',
    'report.sales.commodity': 'Komoditas',
    'report.sales.volumeSold': 'Volume Terjual',
    'report.sales.price': 'Harga',
    'report.sales.volume': 'Volume',
    'report.sales.revenue': 'Total Revenue',
    'report.sales.kg': 'kg',
    
    // Page 4: Marketplace Performance
    'report.marketplace.title': 'PERFORMA MARKETPLACE',
    'report.marketplace.topSelling': 'Produk Terlaris',
    'report.marketplace.highestRevenue': 'Produk Revenue Tertinggi',
    'report.marketplace.avgPrice': 'Rata-rata Harga Jual',
    'report.marketplace.totalRevenue': 'Total Revenue Marketplace',
    'report.marketplace.totalTransactions': 'Total Transaksi',
    'report.marketplace.performanceDetail': 'Detail Performa Produk',
    'report.marketplace.share': '% Share',
    
    // Page 5: Price Trend Analysis
    'report.priceTrend.title': 'ANALISIS TREN HARGA',
    'report.priceTrend.userPrice': 'Harga Anda',
    'report.priceTrend.marketPrice': 'Harga Pasar',
    'report.priceTrend.difference': 'Selisih',
    'report.priceTrend.priceChart': 'Grafik Tren Harga (6 Bulan)',
    'report.priceTrend.insightPositive': 'Produk {commodity} menunjukkan harga jual yang kompetitif dengan margin positif {percentage}% di atas harga pasar. Ini mengindikasikan nilai tambah yang baik dari proses pengolahan dan branding produk. Rekomendasi: pertahankan kualitas premium dan strategi positioning saat ini.',
    
    // Page 6: Partner Growth
    'report.growth.title': 'PERTUMBUHAN MITRA',
    'report.growth.revenueGrowth': 'Revenue Growth',
    'report.growth.volumeGrowth': 'Volume Growth',
    'report.growth.marginGrowth': 'Margin Growth',
    'report.growth.analysisTitle': 'Analisis Pertumbuhan',
    'report.growth.analysisText': 'Berdasarkan data historis, mitra menunjukkan tren pertumbuhan yang positif dengan peningkatan revenue sebesar {revenueGrowth}% dan volume penjualan {volumeGrowth}%. Margin keuntungan juga mengalami peningkatan {marginGrowth}%, menandakan efisiensi operasional yang membaik. Momentum pertumbuhan ini didorong oleh diversifikasi produk dan ekspansi pasar yang efektif.',
    
    // Page 7: Seasonal Demand Forecast
    'report.forecast.title': 'PROYEKSI PERMINTAAN MUSIMAN',
    'report.forecast.subtitle': 'Forecast 6 Bulan Kedepan',
    'report.forecast.period': 'Periode',
    'report.forecast.topProducts': 'Produk Unggulan',
    'report.forecast.projectedGrowth': 'Proyeksi Growth',
    'report.forecast.notes': 'Keterangan',
    'report.forecast.insightsTitle': 'AI Insights & Rekomendasi',
    'report.forecast.insightsText': 'Proyeksi menunjukkan peningkatan demand signifikan untuk produk Coffee di bulan Juni (+30%) dan Seaweed/Moringa di April (+25%). Rekomendasi: tingkatkan kapasitas produksi untuk komoditas tersebut mulai 2 bulan sebelumnya, dan pastikan stok bahan baku mencukupi. Peluang untuk pre-order dan bundling produk sangat potensial di periode peak demand.',
    'report.forecast.month.march': 'Maret',
    'report.forecast.month.april': 'April',
    'report.forecast.month.may': 'Mei',
    'report.forecast.month.june': 'Juni',
    'report.forecast.month.july': 'Juli',
    'report.forecast.month.august': 'Agustus',
    'report.forecast.note.highSeason': 'Musim panen tinggi',
    'report.forecast.note.peakDemand': 'Peak demand musiman',
    'report.forecast.note.moderate': 'Peningkatan moderate',
    'report.forecast.note.festival': 'Festival kopi lokal',
    'report.forecast.note.stable': 'Stabil high demand',
    'report.forecast.note.normalization': 'Normalisasi demand',
    'report.forecast.allProducts': 'Semua Produk',
    
    // Page 8: Financial Report (P&L)
    'report.financial.title': 'LAPORAN LABA RUGI MITRA DESA',
    'report.financial.revenueSection': 'A. REVENUE',
    'report.financial.costSection': 'B. BIAYA PRODUKSI',
    'report.financial.profitSection': 'C. GROSS PROFIT, NET PROFIT & MARGIN',
    'report.financial.product': 'Produk',
    'report.financial.volume': 'Volume',
    'report.financial.sellingPrice': 'Harga Jual/kg',
    'report.financial.costPrice': 'Harga Modal/kg',
    'report.financial.totalRevenue': 'Total Revenue',
    'report.financial.totalCost': 'Total Biaya',
    'report.financial.revenue': 'Revenue',
    'report.financial.cost': 'Biaya',
    'report.financial.netProfit': 'Net Profit',
    'report.financial.margin': 'Margin %',
    'report.financial.total': 'TOTAL',
    'report.financial.totalAvg': 'TOTAL / RATA-RATA',
    
    // Page 9: Strategic Recommendation
    'report.strategy.title': 'STRATEGIC RECOMMENDATION',
    'report.strategy.section1': 'Posisi Pasar dan Performa Saat Ini',
    'report.strategy.section2': 'Optimasi Operasional dan Efisiensi Biaya',
    'report.strategy.section3': 'Strategi Pertumbuhan dan Ekspansi Pasar',
    'report.strategy.generatedBy': 'Report generated by Rural Intelligence Network (RIN)',
    'report.strategy.poweredBy': 'Powered by Timur Network Foundation',
    
    // Common
    'common.save': 'Simpan',
    'common.cancel': 'Batal',
    'common.edit': 'Edit',
    'common.delete': 'Hapus',
    'common.close': 'Tutup',
    'common.search': 'Cari',
    'common.filter': 'Filter',
    'common.loading': 'Loading...',
    'common.success': 'Berhasil',
    'common.error': 'Error',
    'common.confirm': 'Konfirmasi',
    'common.yes': 'Ya',
    'common.no': 'Tidak',
    'common.all': 'Semua',
    'common.none': 'Tidak ada',
  },
  
  en: {
    // Navbar
    'nav.about': 'About',
    'nav.modules': 'Modules',
    'nav.impact': 'Impact',
    'nav.products': 'Products',
    'nav.products.generator': 'AI Product Generator',
    'nav.products.marketplace': 'Rural Marketplace',
    'nav.myProfile': 'My Profile',
    
    // Hero Section
    'hero.title': 'Transforming Rural Potential',
    'hero.title2': 'Into Intelligent Economic Growth',
    'hero.subtitle': 'AI-powered community-owned economic system empowering villages to discover, develop, and distribute value from local resources',
    'hero.join': 'Register as Village Partner',
    'hero.learnMore': 'Learn More',
    'hero.watchDemo': 'Watch Demo',
    
    // Landing Page Sections
    'landing.modules.title': 'RIN Platform Modules',
    'landing.modules.subtitle': 'Complete ecosystem for rural economic transformation',
    'landing.impact.title': 'Real Impact',
    'landing.impact.subtitle': 'Measurable results for communities',
    'landing.products.title': 'Products & Services',
    'landing.products.subtitle': 'Complete solutions for villages',
    
    // About Section
    'about.title': 'What is RIN?',
    'about.description': 'AI-powered community-owned economic platform enabling villages to discover, develop, and distribute value from local resources.',
    'about.data.title': 'Data-Driven',
    'about.data.desc': 'Digitalization of village economic assets into actionable data',
    'about.ai.title': 'AI-Powered',
    'about.ai.desc': 'Smart analysis for strategic decision-making',
    'about.market.title': 'Market Access',
    'about.market.desc': 'Direct connection to markets with transparent pricing',
    
    // Modules Section
    'modules.title': 'Platform Modules',
    'modules.description': 'Complete ecosystem for rural economic transformation',
    'modules.data.title': 'Community Data Engine',
    'modules.data.desc': 'Digitalization of village economic assets, commodities, and capabilities into actionable data',
    'modules.translator.title': 'AI Economic Translator',
    'modules.translator.desc': 'Transformation of raw village data into market insights, pricing strategies, and demand forecasts',
    'modules.generator.title': 'AI Product Generator',
    'modules.generator.desc': 'AI-based product ideation from local commodities with margin analysis and feasibility scoring',
    'modules.marketplace.title': 'Rural Market Link',
    'modules.marketplace.desc': 'Marketplace directly connecting villages to buyers using transparent pricing and smart contracts',
    'modules.impact.title': 'Impact Dashboard',
    'modules.impact.desc': 'Real-time tracking of social and economic impact metrics for stakeholders',
    
    // Impact Section
    'impact.title': 'Real Impact',
    'impact.description': 'Measurable results for communities',
    'impact.villages': 'Partner Villages',
    'impact.products': 'Products Produced',
    'impact.transactions': 'Total Transactions',
    'impact.growth': 'Revenue Growth',
    
    // Showcase Section
    'showcase.title': 'Try AI Product Generator',
    'showcase.description': 'See how our AI generates product recommendations from local commodities',
    'showcase.try': 'Try Now',
    'showcase.from': 'from',
    'showcase.margin': 'Margin',
    'showcase.target': 'Target Market',
    
    // Generator Commodities
    'generator.corn': 'Corn',
    'generator.seaweed': 'Seaweed',
    'generator.moringa': 'Moringa',
    
    // Marketplace Section
    'marketplace.description': 'Digital market for high-quality village products',
    'marketplace.browse': 'Browse Products',
    'marketplace.capacity': 'Capacity',
    
    // Footer
    'footer.description': 'AI-powered community-owned economic platform enabling villages to discover, develop, and distribute value from local resources.',
    'footer.rights': 'Copyright Protected. Powered by Timur Network Foundation.',
    
    // Community Data Engine
    'dataEngine.title': 'Community Data Engine',
    'dataEngine.subtitle': 'Input your village\'s economic assets and production capacity',
    'dataEngine.step1': 'Village Data',
    'dataEngine.step2': 'PIC Data',
    'dataEngine.step3': 'Location Data',
    'dataEngine.step4': 'Production Data',
    'dataEngine.step5': 'Community Assets',
    'dataEngine.step6': 'Review',
    
    // Step 1: Village Data
    'step1.title': 'Village Data',
    'step1.villageName': 'Village Name',
    'step1.villageName.placeholder': 'Enter village name',
    'step1.villageType': 'Village Type',
    'step1.villageType.placeholder': 'Select village type',
    'step1.villageType.agricultural': 'Agricultural',
    'step1.villageType.coastal': 'Coastal',
    'step1.villageType.mountain': 'Mountainous',
    'step1.population': 'Population',
    'step1.population.placeholder': 'Enter population',
    
    // Step 2: PIC Data
    'step2.title': 'PIC Data',
    'step2.picName': 'PIC Name',
    'step2.picName.placeholder': 'Enter PIC name',
    'step2.picRole': 'Role',
    'step2.picRole.placeholder': 'Enter role',
    'step2.picPhone': 'Phone',
    'step2.picPhone.placeholder': 'Enter phone number',
    'step2.picEmail': 'Email',
    'step2.picEmail.placeholder': 'Enter email',
    'step2.fullName': 'Full Name',
    'step2.fullName.placeholder': 'Enter full name',
    'step2.whatsapp': 'WhatsApp',
    'step2.whatsapp.placeholder': 'WhatsApp number',
    'step2.instagram': 'Instagram',
    'step2.instagram.placeholder': 'Instagram username',
    'step2.tiktok': 'TikTok',
    'step2.tiktok.placeholder': 'TikTok username',
    'step2.website': 'Website',
    'step2.website.placeholder': 'Website URL',
    
    // Step 3: Location Data
    'step3.title': 'Location Data',
    'step3.province': 'Province',
    'step3.province.placeholder': 'Select province',
    'step3.district': 'District',
    'step3.district.placeholder': 'Enter district',
    'step3.subdistrict': 'Subdistrict',
    'step3.subdistrict.placeholder': 'Enter subdistrict',
    'step3.address': 'Full Address',
    'step3.address.placeholder': 'Enter full address',
    'step3.coordinates': 'GPS Coordinates',
    'step3.coordinates.placeholder': 'Example: -6.200000, 106.816666',
    'step3.rt': 'RT',
    'step3.rt.placeholder': 'RT number',
    'step3.rw': 'RW',
    'step3.rw.placeholder': 'RW number',
    'step3.kelurahan': 'Kelurahan',
    'step3.kelurahan.placeholder': 'Kelurahan name',
    'step3.kecamatan': 'Kecamatan',
    'step3.kecamatan.placeholder': 'Kecamatan name',
    'step3.city': 'City',
    'step3.city.placeholder': 'City name',
    'step3.postalCode': 'Postal Code',
    'step3.postalCode.placeholder': 'Postal code',
    'step3.pinLocation': 'Pin Location',
    'step3.pinLocation.placeholder': 'Google Maps link',
    
    // Step 4: Production Data
    'step4.title': 'Production Data',
    'step4.description': 'Select commodities produced in your village',
    'step4.selectCommodity': 'Select Commodity',
    'step4.commodityType': 'Commodity Type',
    'step4.addCustomCommodity': 'Add Other Commodity',
    'step4.addCustomCommodity.placeholder': 'Enter commodity name',
    'step4.monthlyVolume': 'Monthly Production Volume',
    'step4.monthlyVolume.placeholder': 'Enter volume (ton)',
    'step4.qualityLevel': 'Quality Level',
    'step4.qualityLevel.placeholder': 'Select quality',
    'step4.harvestSeason': 'Harvest Season',
    'step4.harvestSeason.placeholder': 'Enter harvest season',
    'button.add': 'Add',
    
    // Step 5: Community Assets
    'step5.title': 'Community Assets',
    'step5.workforce': 'Workforce',
    'step5.workforce.placeholder': 'Available workforce',
    'step5.equipment': 'Equipment',
    'step5.equipment.placeholder': 'Description of equipment owned',
    'step5.infrastructure': 'Infrastructure',
    'step5.infrastructure.placeholder': 'Description of supporting infrastructure',
    'step5.skills': 'Community Skills',
    'step5.addCustomSkill': 'Add Other Skill',
    'step5.addCustomSkill.placeholder': 'Enter skill',
    'step5.addCustomEquipment': 'Add Other Equipment',
    'step5.addCustomEquipment.placeholder': 'Enter equipment name',
    'step5.logistics': 'Logistics',
    'step5.addCustomLogistics': 'Add Other Logistics',
    'step5.addCustomLogistics.placeholder': 'Enter logistics type',
    
    // Step 6: Review
    'step6.title': 'Review Data',
    'step6.description': 'Review the data you have entered',
    'step6.submit': 'Submit Data',
    'step6.villageInfo': 'Village Information',
    'step6.picInfo': 'PIC Information',
    'step6.locationInfo': 'Location Information',
    'step6.productionInfo': 'Production Information',
    'step6.assetsInfo': 'Asset Information',
    'step6.edit': 'Edit',
    
    'dataEngine.villageName': 'Village Name',
    'dataEngine.province': 'Province',
    'dataEngine.district': 'District',
    'dataEngine.subdistrict': 'Subdistrict',
    'dataEngine.picName': 'PIC Name',
    'dataEngine.picRole': 'PIC Role',
    'dataEngine.picPhone': 'PIC Phone',
    'dataEngine.picEmail': 'PIC Email',
    'dataEngine.address': 'Full Address',
    'dataEngine.coordinates': 'Coordinates',
    'dataEngine.selectCommodities': 'Select Commodities',
    'dataEngine.production': 'Production',
    'dataEngine.capacity': 'Capacity',
    'dataEngine.quality': 'Quality',
    'dataEngine.workforce': 'Workforce',
    'dataEngine.equipment': 'Equipment',
    'dataEngine.infrastructure': 'Infrastructure',
    'dataEngine.review': 'Review Data',
    'dataEngine.success': 'Data saved successfully!',
    'dataEngine.error': 'Failed to save data',
    
    // AI Product Generator
    'generator.title': 'AI Product Generator',
    'generator.subtitle': 'Product recommendations derived from your commodities',
    'generator.selectCommodity': 'Select Commodity',
    'generator.select': 'Select Main Commodity',
    'generator.generate': 'Generate Recommendations',
    'generator.generating': 'Generating...',
    'generator.results': 'Recommendations Results',
    'generator.productName': 'Product Name',
    'generator.description': 'Description',
    'generator.marketPotential': 'Market Potential',
    'generator.investmentNeeded': 'Investment Needed',
    'generator.roi': 'Estimated ROI',
    'generator.addToMarket': 'Add to Marketplace',
    'generator.complete': 'Recommendations Ready',
    'generator.completeDesc': '{count} derived products from {commodity} have been generated. Select the ones that best match your capacity and target market.',
    'generator.options': 'Product Options',
    'generator.margin': 'Margin',
    'generator.cost': 'Production Cost',
    'generator.price': 'Selling Price',
    'generator.breakeven': 'Break Even',
    'generator.complexity': 'Complexity',
    'generator.risk': 'Risk',
    'generator.viewFull': 'View Full Details',
    'generator.hideDetails': 'Hide Details',
    'generator.reasoning': 'AI Analysis',
    'generator.equipment': 'Required Equipment',
    'generator.shopEquipment': 'Buy Equipment',
    'generator.packaging': 'Packaging',
    'generator.shopPackaging': 'Buy Packaging',
    'generator.cocoa': 'Cocoa',
    'generator.coffee': 'Coffee',
    'generator.cassava': 'Cassava',
    'generator.others': 'Others',
    'generator.othersPlaceholder': 'Enter other commodities (separated by commas)',
    'generator.enterCommodity': 'Enter other commodities (separated by commas)',
    'generator.analyzing': 'Analyzing Commodity',
    'generator.available': 'Available Capacity',
    'generator.readyTitle': 'Ready to Generate Product Recommendations?',
    'generator.readyDesc': 'Select the commodity above and click the Generate button to get product recommendations tailored to your capacity and market opportunities.',
    'generator.lowRisk': 'Low',
    'generator.mediumRisk': 'Medium',
    'generator.highRisk': 'High',
    'generator.lowComplexity': 'Low',
    'generator.mediumComplexity': 'Medium',
    'generator.highComplexity': 'High',
    
    // Buttons
    'button.next': 'Next',
    'button.prev': 'Previous',
    'button.submit': 'Submit',
    'button.save': 'Save',
    'button.cancel': 'Cancel',
    'button.close': 'Close',
    'button.edit': 'Edit',
    'button.delete': 'Delete',
    'button.confirm': 'Confirm',
    'button.back': 'Back',
    'button.continue': 'Continue',
    'button.finish': 'Finish',
    
    // Dashboard
    'dashboard.title': 'Village Dashboard',
    'dashboard.welcome': 'Welcome',
    'dashboard.overview': 'Overview',
    'dashboard.totalRevenue': 'Total Revenue',
    'dashboard.activePartners': 'Active Village Partners',
    'dashboard.totalProducts': 'Total Products',
    'dashboard.commodities': 'Commodities',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.statistics': 'Statistics',
    'dashboard.back': 'Back to Dashboard',
    
    // AI Economic Translator
    'aet.title': 'AI Economic Translator',
    'aet.subtitle': 'Village Economic Data Translator',
    'aet.priceTrend': 'Price Trend Analysis',
    'aet.volumeAnalysis': 'Volume Analysis',
    'aet.filter.period': 'Period Filter',
    'aet.filter.commodity': 'Commodity Filter',
    'aet.filter.daily': 'Daily',
    'aet.filter.weekly': 'Weekly',
    'aet.filter.monthly': 'Monthly',
    'aet.filter.q1': 'Q1',
    'aet.filter.q2': 'Q2',
    'aet.filter.q3': 'Q3',
    'aet.filter.q4': 'Q4',
    'aet.applyFilter': 'Apply Filter',
    'aet.clearFilter': 'Clear Filter',
    
    // Marketplace
    'marketplace.title': 'Rural Marketplace',
    'marketplace.subtitle': 'Village Digital Market',
    'marketplace.search': 'Search products...',
    'marketplace.filter': 'Filter',
    'marketplace.sort': 'Sort',
    'marketplace.addToCart': 'Add to Cart',
    'marketplace.viewDetails': 'View Details',
    'marketplace.price': 'Price',
    'marketplace.stock': 'Stock',
    'marketplace.seller': 'Seller',
    'marketplace.category': 'Category',
    
    // My Profile
    'profile.title': 'My Profile',
    'profile.activePartner': 'Active Village Partner',
    'profile.exportReport': 'Export Report',
    'profile.totalCommodities': 'Total Commodities',
    'profile.monthlyProduction': 'Monthly Production',
    'profile.activeProducts': 'Active Products',
    'profile.currentStock': 'Current Stock',
    'profile.totalRevenue': 'Total Revenue',
    'profile.commodityDetails': 'Commodity Details',
    'profile.updateStock': 'Update Stock',
    'profile.capacity': 'Capacity',
    'profile.derivedProducts': 'Derived Products',
    'profile.monthlySales': 'Monthly Sales',
    'profile.lastUpdate': 'Last Update',
    'profile.addProduct': 'Add Product',
    'profile.addSales': 'Add Sales',
    'profile.myProducts': 'My Products',
    'profile.commodity': 'Commodity',
    'profile.sellingPrice': 'Selling Price',
    'profile.stock': 'Stock',
    'profile.sales': 'Sales',
    'profile.revenue': 'Revenue',
    'profile.ton': 'Ton',
    'profile.kg': 'kg',
    'profile.myProductsMarketplace': 'My Products in Marketplace',
    'profile.price': 'Price',
    'profile.sold': 'Sold',
    'profile.viewAll': 'View All Products',
    'profile.aiProductGenerator': 'AI Product Generator',
    'profile.aiProductGeneratorDesc': 'Generate new products from your commodities',
    'profile.aiEconomicInsights': 'AI Economic Insights',
    'profile.aiEconomicInsightsDesc': 'Deep analysis of your business performance',
    'profile.inputSales': 'Input Sales',
    'profile.inputSalesDesc': 'Record daily/weekly/monthly sales',
    'profile.manageMarketplace': 'Manage Marketplace',
    'profile.manageMarketplaceDesc': 'Set product and prices in marketplace',
    'profile.updateStockTitle': 'Update Commodity Stock',
    'profile.updateStockDesc': 'Add new production or manually reduce stock',
    'profile.selectCommodity': 'Select Commodity',
    'profile.selectCommodityPlaceholder': '-- Select Commodity --',
    'profile.updateType': 'Update Type',
    'profile.addProduction': 'Add Production',
    'profile.manualReduction': 'Manual Reduction',
    'profile.amount': 'Amount',
    'profile.amountPlaceholder': 'Enter amount',
    'profile.date': 'Date',
    'profile.notes': 'Notes (Optional)',
    'profile.notesPlaceholder': 'Add notes...',
    'profile.cancel': 'Cancel',
    'profile.saveUpdate': 'Save Stock Update',
    'profile.saveUpdateStock': 'Save Stock Update',
    'profile.enterAmount': 'Enter amount',
    'profile.notesOptional': 'Notes (Optional)',
    'profile.addNotes': 'Add notes...',
    'profile.selectCommodityError': 'Select commodity and enter amount',
    'profile.amountError': 'Amount must be greater than 0',
    'profile.addStockSuccess': 'Successfully added {amount} ton {commodity}',
    'profile.reduceStockSuccess': 'Successfully reduced {amount} ton {commodity}',
    'profile.addProductNew': 'Add New Product',
    'profile.addProductDesc': 'Add new product to your marketplace',
    'profile.productName': 'Product Name',
    'profile.productNamePlaceholder': 'Example: Premium Organic Corn Flour',
    'profile.category': 'Category',
    'profile.commodityCategory': 'Commodity',
    'profile.processedProducts': 'Processed Products',
    'profile.equipment': 'Equipment',
    'profile.baseCommodity': 'Base Commodity',
    'profile.baseCommodityPlaceholder': '-- Select Commodity --',
    'profile.initialStock': 'Initial Stock',
    'profile.sellingPricePerKg': 'Selling Price per Kg',
    'profile.costPricePerKg': 'Cost Price per Kg',
    'profile.minOrder': 'Minimum Order (kg)',
    'profile.productDescription': 'Product Description',
    'profile.productDescPlaceholder': 'Describe quality, production process, product advantages...',
    
    // Export Report PDF
    'report.cover.title': 'VILLAGE PARTNER REPORT',
    'report.cover.subtitle': 'Rural Intelligence Network',
    'report.cover.partnerName': 'Partner Name',
    'report.cover.location': 'Location',
    'report.cover.reportPeriod': 'Report Period',
    'report.cover.generatedDate': 'Generated Date',
    'report.cover.tagline1': 'Data is not just numbers.',
    'report.cover.tagline2': 'It is the foundation for sustainable rural economic growth.',
    'report.cover.poweredBy': 'Powered by Timur Network Foundation',
    
    // Page 2: Commodity Profile
    'report.commodity.title': 'COMMODITY PROFILE',
    'report.commodity.name': 'Commodity',
    'report.commodity.currentStock': 'Current Stock',
    'report.commodity.capacity': 'Capacity',
    'report.commodity.production': 'Production/Month',
    'report.commodity.lastUpdate': 'Last Update',
    'report.commodity.totalStock': 'Total Stock',
    'report.commodity.utilization': 'Utilization Rate',
    'report.commodity.ton': 'ton',
    
    // Page 3: Sales Data
    'report.sales.title': 'SALES DATA',
    'report.sales.totalVolume': 'Total Volume Sold',
    'report.sales.totalTransactions': 'Total Transactions',
    'report.sales.totalRevenue': 'Total Revenue',
    'report.sales.topByVolume': 'Top Products (Volume)',
    'report.sales.topByRevenue': 'Top Products (Revenue)',
    'report.sales.product': 'Product',
    'report.sales.commodity': 'Commodity',
    'report.sales.volumeSold': 'Volume Sold',
    'report.sales.price': 'Price',
    'report.sales.volume': 'Volume',
    'report.sales.revenue': 'Total Revenue',
    'report.sales.kg': 'kg',
    
    // Page 4: Marketplace Performance
    'report.marketplace.title': 'MARKETPLACE PERFORMANCE',
    'report.marketplace.topSelling': 'Top Selling Product',
    'report.marketplace.highestRevenue': 'Highest Revenue Product',
    'report.marketplace.avgPrice': 'Average Selling Price',
    'report.marketplace.totalRevenue': 'Total Marketplace Revenue',
    'report.marketplace.totalTransactions': 'Total Transactions',
    'report.marketplace.performanceDetail': 'Product Performance Details',
    'report.marketplace.share': '% Share',
    
    // Page 5: Price Trend Analysis
    'report.priceTrend.title': 'PRICE TREND ANALYSIS',
    'report.priceTrend.userPrice': 'Your Selling Price',
    'report.priceTrend.marketPrice': 'Market Price',
    'report.priceTrend.difference': 'Difference',
    'report.priceTrend.priceChart': 'Price Chart (6 Months)',
    'report.priceTrend.insightPositive': 'Product {commodity} shows competitive selling prices with a positive margin of {percentage}% above market price. This indicates good value addition from processing and branding efforts. Recommendation: maintain premium quality and current positioning strategy.',
    
    // Page 6: Partner Growth
    'report.growth.title': 'PARTNER GROWTH ANALYSIS',
    'report.growth.revenueGrowth': 'Revenue Growth',
    'report.growth.volumeGrowth': 'Volume Growth',
    'report.growth.marginGrowth': 'Margin Growth',
    'report.growth.analysisTitle': 'Growth Analysis',
    'report.growth.analysisText': 'Based on historical data, the partner shows a positive growth trend with revenue increases of {revenueGrowth}% and sales volume {volumeGrowth}%. Profit margins also increased by {marginGrowth}%, indicating improved operational efficiency. This growth momentum is driven by product diversification and effective market expansion.',
    
    // Page 7: Seasonal Demand Forecast
    'report.forecast.title': 'SEASONAL DEMAND FORECAST',
    'report.forecast.subtitle': '6-Month Forecast',
    'report.forecast.period': 'Period',
    'report.forecast.topProducts': 'Top Products',
    'report.forecast.projectedGrowth': 'Projected Growth',
    'report.forecast.notes': 'Notes',
    'report.forecast.insightsTitle': 'AI Insights & Recommendations',
    'report.forecast.insightsText': 'Forecast shows significant demand increase for Coffee in June (+30%) and Seaweed/Moringa in April (+25%). Recommendation: increase production capacity for these commodities 2 months in advance and ensure sufficient raw material stock. Pre-order and product bundling opportunities are highly potential during peak demand periods.',
    'report.forecast.month.march': 'March',
    'report.forecast.month.april': 'April',
    'report.forecast.month.may': 'May',
    'report.forecast.month.june': 'June',
    'report.forecast.month.july': 'July',
    'report.forecast.month.august': 'August',
    'report.forecast.note.highSeason': 'High Harvest Season',
    'report.forecast.note.peakDemand': 'Peak Seasonal Demand',
    'report.forecast.note.moderate': 'Moderate Increase',
    'report.forecast.note.festival': 'Local Coffee Festival',
    'report.forecast.note.stable': 'Stable High Demand',
    'report.forecast.note.normalization': 'Demand Normalization',
    'report.forecast.allProducts': 'All Products',
    
    // Page 8: Financial Report (P&L)
    'report.financial.title': 'VILLAGE PARTNER PROFIT & LOSS STATEMENT',
    'report.financial.revenueSection': 'A. REVENUE',
    'report.financial.costSection': 'B. PRODUCTION COST',
    'report.financial.profitSection': 'C. GROSS PROFIT, NET PROFIT & MARGIN',
    'report.financial.product': 'Product',
    'report.financial.volume': 'Volume',
    'report.financial.sellingPrice': 'Selling Price/kg',
    'report.financial.costPrice': 'Cost Price/kg',
    'report.financial.totalRevenue': 'Total Revenue',
    'report.financial.totalCost': 'Total Cost',
    'report.financial.revenue': 'Revenue',
    'report.financial.cost': 'Cost',
    'report.financial.netProfit': 'Net Profit',
    'report.financial.margin': 'Margin %',
    'report.financial.total': 'TOTAL',
    'report.financial.totalAvg': 'TOTAL / AVERAGE',
    
    // Page 9: Strategic Recommendation
    'report.strategy.title': 'STRATEGIC RECOMMENDATION',
    'report.strategy.section1': 'Market Position and Current Performance',
    'report.strategy.section2': 'Operational Optimization and Cost Efficiency',
    'report.strategy.section3': 'Growth Strategy and Market Expansion',
    'report.strategy.generatedBy': 'Report generated by Rural Intelligence Network (RIN)',
    'report.strategy.poweredBy': 'Powered by Timur Network Foundation',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.close': 'Close',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.loading': 'Loading...',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.all': 'All',
    'common.none': 'None',
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('id');

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLang = localStorage.getItem('rin-language') as Language;
    if (savedLang && (savedLang === 'id' || savedLang === 'en')) {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('rin-language', lang);
  };

  const t = (key: string, params?: Record<string, string>): string => {
    // Direct access to flat key structure
    const translation = translations[language][key];
    if (translation && params) {
      return Object.keys(params).reduce((acc, paramKey) => {
        return acc.replace(`{${paramKey}}`, params[paramKey]);
      }, translation);
    }
    return translation || key; // Return translation or key as fallback
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    // During hot reload or initial mount, provide a fallback
    // This prevents the warning during development
    return {
      language: 'id' as Language,
      setLanguage: () => {},
      t: (key: string, params?: Record<string, string>) => {
        // Simple fallback translator
        if (params) {
          return Object.keys(params).reduce((acc, paramKey) => {
            return acc.replace(`{${paramKey}}`, params[paramKey]);
          }, key);
        }
        return key;
      }
    };
  }
  return context;
}